[theme]
primaryColor = "#E57373"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#E0E0E0"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "auto"
showSidebarNavigation = true

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
headless = true
runOnSave = true
